### ISSUE TITLE
Document JSON input format and ensure broken JSON doesn't take down the app

### ISSUE THREAD

**Issue by cbredesen** [redhataccess/elixir#2]
Today it is possible to crash Elixir with broken input JSON. Shield from that. Additionally, document the JSON format in README.md (maybe consider moving the technical details to BUILDING.md).

**Comment by aprajshekhar** [comment]
Changes in https://github.com/redhataccess/elixir/pull/1 fixes Elixir breakage with invalid JSON. If JSON for a particular work stream is invalid/broken, the work stream name is logged and the data is skipped. Elixir will display the data of the remaining work streams.
